/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

wyjscie *
obliczenia_1_svc(wejscie *argp, struct svc_req *rqstp)
{
	static wyjscie  result;

	/*
	 * insert server code here
	 */


    for (int i = 0, j = 0; j < strlen(argp->dane_wej); ++i, j += 2) {
        sprintf(result.dane_wyj+j,"%02x", argp->dane_wej[i] & 0xff);
    }
    printf("Hex:%s",result.dane_wyj);
    

	return &result;
}
